### ISSUE TITLE
okw example for Cookie Demo 

### ISSUE THREAD

**Issue by Jbutler-helpful** [PubInv/project-data#52]

**Comment by RobertLRead** [comment]
I created three files in response to this:

1.Rob's Dessert Kitchen (OKW):  https://github.com/helpfulengineering/library/blob/main/alpha/okw/RobDessertKitchen.yml
2. Generic Grocery (OKW): https://github.com/helpfulengineering/library/blob/main/alpha/okw/GenericGrocery.yml
3. Quaker Oats Vanishing Oatmeal Cookie (OKH): https://github.com/helpfulengineering/library/blob/main/alpha/okh/okh-quaker-oats-oatmeal-recipe.yml

Note: I intentially do not have eggs in Rob's Dessert Kitchen's inventory, so that it will be forced to obtain them from a Generic Grocery. However, I don't think the other participants in this exercise should necessarily do that; they can copy my inventory and add the "eggs" entry from the Generic Grocery and avoid a (symbolic) trip to the Generic Grocery story via the matching algorithm.

**Comment by devhawk** [comment]
Can we close this @Jbutler-helpful ?

**Comment by Jbutler-helpful** [comment]
We have made a few a this point but here is one example 
https://github.com/helpfulengineering/library/blob/main/alpha/okh/okh-chococolate-chip-cookies-recipe.yml

you can check the library for current recipe 
https://github.com/helpfulengineering/library/tree/main/alpha/okh
